language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm run-script lint
  - npm run-script cover
  - npm run-script bench

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
