language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - npm install -g gulp
  - npm install -g matcha

script:
  - gulp
  - matcha

after_script:
  - npm install -g coveralls
  - cat ./coverage/lcov.info | coveralls
